service: basic-serverless-lambda

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-southeast-1

plugins:
  - serverless-offline

functions:
  createItem:
    handler: src/handler.createItem
    events:
      - http:
          path: items
          method: post
          cors: true

  listItems:
    handler: src/handler.listItems
    events:
      - http:
          path: items
          method: get
          cors: true

  getItem:
    handler: src/handler.getItem
    events:
      - http:
          path: items/{id}
          method: get
          cors: true

  updateItem:
    handler: src/handler.updateItem
    events:
      - http:
          path: items/{id}
          method: put
          cors: true

  deleteItem:
    handler: src/handler.deleteItem
    events:
      - http:
          path: items/{id}
          method: delete
          cors: true

  deleteAllItems:
    handler: src/handler.deleteAllItems
    events:
      - http:
          path: items
          method: delete
          cors: true